name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Application
        run: |
          # CONFIGURATION_BUILD_DIR yerine -derivedDataPath kullanıyoruz
          xcodebuild clean build \
            -project "SwByeDPI.xcodeproj" \
            -scheme "ByeDPI" \
            -destination "generic/platform=iOS" \
            -configuration Release \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            -derivedDataPath ./DerivedData

          # Payload klasörünü oluştur
          mkdir -p Payload
          
          # Xcode'un oluşturduğu alt klasörlerdeki .app dosyasını bul ve Payload'a kopyala
          find ./DerivedData/Build/Products -type d -name "ByeDPI.app" -exec cp -R {} Payload/ \;
          
          # IPA olarak paketle
          zip -r SwByeDPI.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SwByeDPI-IPA
          path: SwByeDPI.ipa
